spring:
  application:
    name: ledger
  profiles:
    default: postman
  datasource:
    url: jdbc:h2:mem:ledgerdb;DB_CLOSE_DELAY=-1;LOCK_TIMEOUT=10000
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate.format_sql: true
    show-sql: false
  flyway:
    enabled: false
    locations: classpath:db/migration
  h2:
    console:
      enabled: true

ledger:
  external-logging:
    base-url: https://httpstat.us
    path: /200
    connect-timeout-ms: 2000
    read-timeout-ms: 2000

---

spring:
  config:
    activate:
      on-profile: demo

ledger:
  external-logging:
    enabled: false

---

spring:
  config:
    activate:
      on-profile: prod

ledger:
  external-logging:
    enabled: true
    base-url: https://httpstat.us
    path: /200

---

spring:
  config:
    activate:
      on-profile: postman

ledger:
  external-logging:
    enabled: true
    base-url: https://postman-echo.com
    path: /status/200
