-- Production schema (used when Flyway is enabled). Mirrors the JPA entities.
create table account (
    id          bigint generated by default as identity primary key,
    user_id     bigint not null,
    currency    varchar(3) not null,
    balance     numeric(38, 4) not null default 0,
    row_version bigint not null default 0,
    created_at  timestamp not null default current_timestamp,
    constraint chk_account_balance_non_negative check (balance >= 0)
);
create index idx_account_user on account (user_id);

create table account_transaction (
    id                      bigint generated by default as identity primary key,
    account_id              bigint not null references account (id),
    txn_type                varchar(20) not null,
    amount                  numeric(38, 4) not null,
    balance_after           numeric(38, 4) not null,
    currency                varchar(3) not null,
    counterparty_account_id bigint,
    description             varchar(255),
    created_at              timestamp not null default current_timestamp,
    constraint chk_txn_amount_positive check (amount > 0)
);
-- Supports cursor (seek) pagination: newest-first by id within an account.
create index idx_txn_account_id_desc on account_transaction (account_id, id desc);
